[colors.primary]
background = "#21252B"
bright_foreground = "#7F848E"
dim_foreground = "#ABB2BF"
foreground = "#E6E6E6"

[colors.normal]
black = "#1D1F23"
white = "#E6E6E6"
red = "#E06C75"
#orange = "#D19A66"
yellow = "#E6C07B"
green = "#98C379"
cyan = "#56B6C2"
blue = "#5680C2"
magenta = "#C678DD"



[colors.bright]
black = "#7F848E"
white = "#E6E6E6"
red = "#E06C75"
#orange = "#D19A66"
yellow = "#E6C07B"
green = "#98C379"
cyan = "#56B6C2"
blue = "#5680C2"
magenta = "#C678DD"

#base0 = "#1D1F23"
#base1 = "#21252B"
#base2 = "#282C34"
#base3 = "#2C313C"
#base4 = "#333A42"
#base5 = "#404859"
#base6 = "#495162"
#base7 = "#7F848E"
#base8 = "#9DA5B4"
#base9 = "#ABB2BF"
#base10 = "#E6E6E6"
