[colors.primary]
background = "#21252B"
bright_foreground = "#6C7280"
dim_foreground = "#ABB2BF"
foreground = "#E6E6E6"

[colors.normal]
black = "#1D1F23"
white = "#E6E6E6"
red = "#E27881"
yellow = "#EAC786"
green = "#98C379"
cyan = "#62BAC6"
blue = "#71B9F4"
magenta = "#C88BDA"

[colors.bright]
black = "#6C7280"
white = "#E6E6E6"
red = "#E27881"
yellow = "#EAC786"
green = "#98C379"
cyan = "#62BAC6"
blue = "#71B9F4"
magenta = "#C88BDA"

#magenta   = "#C88BDA"
#red       = "#E27881"
#orange    = "#E79C7E"
#yellow    = "#EAC786"
#green     = "#98C379"
#cyan      = "#62BAC6"
#blue      = "#71B9F4"
#text      = "#E6E6E6"
#subtext1  = "#C9CCD3"
#subtext0  = "#ABB2BF"
#overlay2  = "#969DAB"
#overlay1  = "#818896"
#overlay0  = "#6C7280"
#surface2  = "#5B626D"
#surface1  = "#4A505A"
#surface0  = "#393E47"
#base      = "#282C34"
#mantle    = "#21252B"
#crust     = "#1D1F23"
